# Matrizes em Python

## Inicialização

In [ ]:
import numpy as np #biblioteca para manipulacao de dados

Matriz de zeros

In [ ]:
mA = np.zeros((3,5))
print(mA)
type(mA)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


numpy.ndarray

Matriz de um

In [ ]:
mB = np.ones((3,5))
print(mB)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Matriz identidade

In [ ]:
I = np.eye((5))
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Matriz diagonal

In [ ]:
# matriz diagonal com os elementos explícitos
mC = np.diag([5,6,7,8])
print("matriz diagonal com os elementos explícitos")
print(mC)

# elementos abaixo da diagonal principal
mD = np.diag([1,1,1,1],-2)
print("elementos abaixo da diagonal principal")
print(mD)

# elementos acima da diagonal principal
mE = np.diag([1,1,1,1],+2)
print("elementos acima da diagonal principal")
print(mE)

matriz diagonal com os elementos explícitos
[[5 0 0 0]
 [0 6 0 0]
 [0 0 7 0]
 [0 0 0 8]]
elementos abaixo da diagonal principal
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]]
elementos acima da diagonal principal
[[0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


Matriz aleatória

In [ ]:
R = np.random.rand(3,5)
print(R)

[[0.01627762 0.80012187 0.26762793 0.00937266 0.99257335]
 [0.89444919 0.4327392  0.58780142 0.97853467 0.01310809]
 [0.93732616 0.0098092  0.92368913 0.88135793 0.89090653]]


Matriz a partir de listas

In [ ]:
L = [[1,2,3,4,231],[5,6,7,8,238],[9,10,11,12,213]]
L = np.array(L) #converter a lista em um array
print(L)

[[  1   2   3   4 231]
 [  5   6   7   8 238]
 [  9  10  11  12 213]]


## Acessar elementos da matriz

In [ ]:
L[1,3]

8

In [ ]:
# operador dois pontos
linha0 = L[[0],:]
print(linha0)
print(linha0.shape)

[[  1   2   3   4 231]]
(1, 5)


In [ ]:
R[:,[0,2]]

array([[0.01627762, 0.26762793],
       [0.89444919, 0.58780142],
       [0.93732616, 0.92368913]])

In [ ]:
mD

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]])

In [ ]:
mD[0:3,:]

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0]])

In [ ]:
mD[:,0:3]

array([[0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

# Eliminação de Gauss

In [ ]:
import numpy as np
#import pandas as pd - utilizado apenas na impressão de algumas matrizes

**1) Inicialização de uma matriz A de dimensão 3x3 e uma matriz b de dimensão 3x1 com números aleatórios**

In [ ]:
A = np.random.rand(3,3)
print(A)

[[0.65044607 0.16268303 0.18162854]
 [0.26867134 0.76060339 0.52207638]
 [0.10031237 0.42524594 0.91683295]]


In [ ]:
b = np.random.rand(3,1)
print(b)

[[0.86985676]
 [0.30879292]
 [0.79991877]]


**2) Qual o valor do primeiro multiplicador? Não utilize os números e sim referências a matriz.**

In [ ]:
pivo = A[0,0]
m = -(A[1,0]/pivo)

linha0 = A[[0],:]
linha1 = A[[1],:]

cA = A #copia de A
cA[1] = (m*linha0)+linha1
print("A = ",cA)
print()
cb = b #copia de b
cb[1] = (m*cb[0])+cb[1]
print("b = ",cb)

A =  [[0.65044607 0.16268303 0.18162854]
 [0.         0.69340602 0.44705343]
 [0.10031237 0.42524594 0.91683295]]

b =  [[ 0.86985676]
 [-0.05050755]
 [ 0.79991877]]


**3. Determine o próximo multiplicador e atualize a linha 2 das matrizes A e b.**

In [ ]:
m = -(A[2,0]/pivo)

linha2 = A[[2],:]
cA[2] = (m*linha0)+linha2
print("A = ", cA)
print()
cb[2] = (m*cb[0])+cb[2]
print("b = ",cb)

A =  [[0.65044607 0.16268303 0.18162854]
 [0.         0.69340602 0.44705343]
 [0.         0.40015681 0.88882204]]

b =  [[ 0.86985676]
 [-0.05050755]
 [ 0.66576868]]


**4. O trabalho com a primeira coluna está finalizado. Determine o próximo pivô.**

In [ ]:
pivo = A[1,1]

**5. Determine o próximo multiplicador e atualize a linha 2.**

In [ ]:
m = -(A[2,1]/pivo)

linha1 = A[[1],:]
linha2 = A[[2],:]
cA[2] = (m*linha1)+linha2
print("A = ",cA)
print()
cb[2] = (m*cb[1]) + cb[2]
print("b = ",cb)

A =  [[0.65044607 0.16268303 0.18162854]
 [0.         0.69340602 0.44705343]
 [0.         0.         0.63083253]]

b =  [[ 0.86985676]
 [-0.05050755]
 [ 0.69491602]]


**Agora a matriz A está em um formato triangular superior e precisamos determinar os valores de `x[0]`, `x[1]` e `x[2]`.**

In [ ]:
x = np.zeros(3)
x[2] = b[2]/A[2,2]
x[1] = (b[1]-(A[1,2]*x[2]))/A[1,1]
x[0] = (b[0]-(A[0,2]*x[2])-(A[0,1]*x[1]))/A[0,0]

print(x)

[ 1.22556997 -0.78305515  1.10158558]


**VERIFICANDO O RESULTADO**

In [ ]:
A @ x

array([ 0.86985676, -0.05050755,  0.69491602])

In [ ]:
b

array([[ 0.86985676],
       [-0.05050755],
       [ 0.69491602]])

# Eliminação Gaussiana sem pivoteamento

**Função que realiza a primeira parte da eliminação gaussiana, convertendo a matriz em uma matriz triangular superior.**

In [ ]:
import numpy as np

In [ ]:
matriz_coeficientes = np.array([[3,2,7],[-6,5,1],[3,11,-1]])
print(matriz_coeficientes)
print()
termos_independentes = np.array([8,-10,-9])
print(termos_independentes)

[[ 3  2  7]
 [-6  5  1]
 [ 3 11 -1]]

[  8 -10  -9]


In [ ]:
def eliminacao_gaussiana(matriz_coeficientes, termos_independentes):
    '''
    matriz_coeficientes é uma matriz n x n
    termos_independentes é uma matriz n por 1
    '''

    A = matriz_coeficientes
    b = termos_independentes
    tamanho = len(A)

    for k in range(0, tamanho-1):
        pivo = A[k,k]
        for i in range(k+1, tamanho):
            m = - (A[i,k] / pivo)
            A[i] = (m * A[k]) + A[i]
            b[i] = (m * b[k]) + b[i]

    return A, b

In [ ]:
A,b = eliminacao_gaussiana(matriz_coeficientes, termos_independentes)
print(A)
print()
print(b)

[[  3   2   7]
 [  0   9  15]
 [  0   0 -23]]

[  8   6 -23]


**Função que determina as soluções x[j] de um sistema com matriz de coeficientes triangular superior.**

In [ ]:
def triangular_superior(A, b):
    '''
    A: matriz triangular superior
    b: termos independentes do sistema triangular superior

    retorna a solução do sistema
    '''
    tamanho = len(A)

    x = np.zeros(tamanho)
    x[tamanho-1] = b[tamanho-1] / A[tamanho-1, tamanho-1] # ultimo x[j]

    #range(inicio,parada,passo)
    for k in range(tamanho-2,-1,-1):
        for t in range(k,tamanho):
            b[k] = b[k] - (A[k,t] * x[t])

        x[k] = b[k] / A[k,k]

    return x

In [ ]:
x = triangular_superior(A, b)
print(x)

[ 1. -1.  1.]


In [ ]:
print(matriz_coeficientes @ x)

[  8.   6. -23.]


# E se um pivô for igual a zero?

In [ ]:
def resolver_sistema(matriz_coeficientes, termos_independentes):
    tA, tb = eliminacao_gaussiana(matriz_coeficientes, termos_independentes)
    x = triangular_superior(tA, tb)
    return x

In [ ]:
matriz_coeficientes[0,0] = 10 ** -16
print(matriz_coeficientes)
print()

x = resolver_sistema(matriz_coeficientes,termos_independentes)
print('x = ',x)

[[  0   2   7]
 [  0   9  15]
 [  0   0 -23]]



<ipython-input-16-ae18a835d23d>:14: RuntimeWarning: invalid value encountered in long_scalars
  m = - (A[i,k] / pivo)


ValueError: ignored

In [ ]:
matriz_coeficientes = np.array([[3,2,1,-1],[0,0,1,3],[0,-3,-5,7],[0,2,4,0]])
termos_independentes = np.array([5,6,7,15])
print(matriz_coeficientes)
print()
x = resolver_sistema(matriz_coeficientes,termos_independentes)
print('x = ',x)

[[ 3  2  1 -1]
 [ 0  0  1  3]
 [ 0 -3 -5  7]
 [ 0  2  4  0]]



<ipython-input-16-ae18a835d23d>:14: RuntimeWarning: divide by zero encountered in long_scalars
  m = - (A[i,k] / pivo)
<ipython-input-16-ae18a835d23d>:15: RuntimeWarning: invalid value encountered in multiply
  A[i] = (m * A[k]) + A[i]


OverflowError: ignored

**SOLUÇÃO: PIVOTEAMENTO**