# Interação com o usuário

Exibição de dados na tela

In [ ]:
valor1 = 68
print(valor1) #a função "print" é utilizada para imprimir

68


Leitura de dados do teclado

In [ ]:
valor2 = input()
print("A pessoa digitou o valor:", valor2) #Imprimindo o valor digitado pelo usuário

16
A pessoa digitou o valor: 16


# Operações

In [ ]:
2 + 2 #adição
# nao salva em variavel

4

In [ ]:
9 - 6 #subtração

3

In [ ]:
3 * 54 #multiplicação

162

In [ ]:
11 / 2 #divisão

5.5

In [ ]:
11 // 2 #parte inteira (divisão inteira)

5

In [ ]:
11 % 2 #resto da divisao

1

In [ ]:
11 ** 2 #exponenciação

121

# Variáveis

Não precisa declarar explicitamente o tipo da variável

- string ou str: Sequência de caracteres, geralmente utilizada para representar palavras, frases ou textos.
- float: Armazena números com ponto flutuante (reais)
- int: Números inteiros.
- boolean ou bool: True ou False
- list: Sequência de variáveis, onde cada elemento pode ser manipulado separadamente. É Definida usando [ ].

In [ ]:
A = 8.6453093
B = 8.6449279

r1 = (A - B) ** 2
print(r1)

r2 = A**2 + B**2 - 2*(A*B)
print(r2)

r3 = A**2 - 2*(A*B) + B**2
print(r3)

r4 = A**2 - B*(2*A) + B**2
print(r4)

1.454659599987962e-07
1.4546597526532423e-07
1.4546596105446952e-07
1.4546596105446952e-07


In [ ]:
variavel_qualquer

NameError: ignored

In [ ]:
# tipo da variavel
type(A)

float

In [ ]:
numero_inteiro = 5
type(numero_inteiro)

int

## Cadeia de caracteres (String)

In [ ]:
# olá mundo

print("Olá Mundo")
type("Olá Mundo")

Olá Mundo


str

In [ ]:
type('Maíra'), type("Maíra"), type("""Maíra"""), type('''Maíra''')

(str, str, str, str)

In [ ]:
nome1 = "Maíra Santana"
print(nome1)

nome = '''Maíra
Santana'''
print(nome)

Maíra Santana
Maíra
Santana


In [ ]:
nome = 'Maíra\nSantana'
print(nome)

Maíra
Santana


## Booleano

In [ ]:
# verdadeiro ou falso

True, False, type(True), type(False)

(True, False, bool, bool)

In [ ]:
# operadores lógicos 'and' 'or'
True and True, True and False, False and True, False and False

(True, False, False, False)

In [ ]:
True or True, True or False, False or True, False or False

(True, True, True, False)

In [ ]:
# menor: <
# menor ou igual: <=
# maior: >
# maior ou igual: >=
# igual: ==
# diferente: |=

# da para comparar numeros e/ou sequencia de caracteres

# Desvios lógicos

In [ ]:
idade = 65

if idade >= 65:
  print('Essa pessoa é idosa e tem', idade, 'anos')

Essa pessoa é idosa e tem 65 anos


In [ ]:
idade = 19

if idade >= 65:
  print('Essa pessoa é idosa e tem', idade, 'anos')
elif idade > 18:
  print('Essa pessoa não é idosa e tem', idade, 'anos')
else:
  print('Essa pessoa é menor de idade e tem', idade, 'anos')

Essa pessoa não é idosa e tem 19 anos


# Funções

In [ ]:
def classificarIdade(idade):
  if idade >= 65:
    print('Essa pessoa é idosa e tem', idade, 'anos')
  elif idade > 18:
    print('Essa pessoa é maior de idade, mas não é idosa, pois tem', idade, 'anos')
  else:
    print('Essa pessoa é menor de idade e tem', idade, 'anos')

#classificarIdade(45)


In [ ]:
classificarIdade(45)

Essa pessoa é maior de idade, mas não é idosa, pois tem 45 anos


In [ ]:
classificarIdade(50)

Essa pessoa é maior de idade, mas não é idosa, pois tem 50 anos


In [ ]:
classificarIdade(22)

Essa pessoa é maior de idade, mas não é idosa, pois tem 22 anos


In [ ]:
classificarIdade(4)

Essa pessoa é menor de idade e tem 4 anos


# Estruturas de repetição - laços/loops

In [ ]:
idades = [13,26,75]
classificarIdade(idades[0])
classificarIdade(idades[1])
classificarIdade(idades[2])

Essa pessoa é menor de idade e tem 13 anos
Essa pessoa é maior de idade, mas não é idosa, pois tem 26 anos
Essa pessoa é idosa e tem 75 anos


##for

In [ ]:
for i in idades:
  classificarIdade(i)

Essa pessoa é menor de idade e tem 13 anos
Essa pessoa é maior de idade, mas não é idosa, pois tem 26 anos
Essa pessoa é idosa e tem 75 anos


In [ ]:
idades.append(92)

In [ ]:
print(idades)

[13, 26, 75, 92]


In [ ]:
for i in range(0,3):
  classificarIdade(idades[i])

Essa pessoa é menor de idade e tem 13 anos
Essa pessoa é maior de idade, mas não é idosa, pois tem 26 anos
Essa pessoa é idosa e tem 75 anos


In [ ]:
# só executar os da posição par
for i in range(0,len(idades),2):
  classificarIdade(idades[i])

Essa pessoa é menor de idade e tem 13 anos
Essa pessoa é idosa e tem 75 anos


##while

In [ ]:
i = 0
while i < 3:
  classificarIdade(idades[i])
  i+=1 # i = i + 1

Essa pessoa é menor de idade e tem 13 anos
Essa pessoa é maior de idade, mas não é idosa, pois tem 26 anos
Essa pessoa é idosa e tem 75 anos


# Sequência/listas de valores

In [ ]:
lista = []
type(lista)

list

In [ ]:
numeros1 = [1,2,3,4,5,6,7,8,9,10]
print(numeros1)

numeros2 = list(range(1,11))
print(numeros2)

# uma unica lista pode receber dados de tipos diferentes

dadosPessoa = ['Maíra',27,'Engenheira Biomédica',1.66,True]
print(dadosPessoa)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
['Maíra', 27, 'Engenheira Biomédica', 1.66, True]


## Acessar conteúdo da lista

In [ ]:
print(dadosPessoa[0])
print(dadosPessoa[2])

Maíra
Engenheira Biomédica


In [ ]:
# tamanho da lista
len(dadosPessoa)

5

In [ ]:
# pegar dados dos ultimos indices da lista
dadosPessoa[len(dadosPessoa)-1]

True

In [ ]:
dadosPessoa[-2] #indice negativo - ele entende que você quer pegar de tras pra frente

1.66

## Fatiamento de uma lista

In [ ]:
dadosPessoa[0:3]

['Maíra', 27, 'Engenheira Biomédica']

In [ ]:
dadosPessoa[1:3]

[27, 'Engenheira Biomédica']

In [ ]:
dadosPessoa[:] #retorna todos os valores

['Maíra', 27, 'Engenheira Biomédica', 1.66, True]

In [ ]:
# pegar so os valores pares
numeros2[1:10:2]

[2, 4, 6, 8, 10]

In [ ]:
# pegar so os valores ímpares
numeros2[0:11:2]

[1, 3, 5, 7, 9]

In [ ]:
# criar lista apenas dos numeros ímpares
list(range(1,32,2))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31]

In [ ]:
# criar lista apenas dos numeros pares
list(range(0,32,2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]

In [ ]:
# dá também para pegar parte de uma string
nome = 'Maira Santana'
nome[0], nome[:6]

('M', 'Maira ')

In [ ]:
# adição ou remoção de sequencia de caracteres
dir(nome) #mostra as operacoes que eu posso fazer em uma determinada variavel

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [ ]:
help(nome.rsplit) #mostra como posso utilizar um determinado comando/operacao

Help on built-in function rsplit:

rsplit(sep=None, maxsplit=-1) method of builtins.str instance
    Return a list of the words in the string, using sep as the delimiter string.
    
      sep
        The delimiter according which to split the string.
        None (the default value) means split according to any whitespace,
        and discard empty strings from the result.
      maxsplit
        Maximum number of splits to do.
        -1 (the default value) means no limit.
    
    Splits are done starting at the end of the string and working to the front.



In [ ]:
numeros = list(range(1,11))
print(numeros)
dir(numeros)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [ ]:
# remover
help(numeros.pop)

Help on built-in function pop:

pop(index=-1, /) method of builtins.list instance
    Remove and return item at index (default last).
    
    Raises IndexError if list is empty or index is out of range.



In [ ]:
numeros.pop()
print(numeros)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
#adicionar
numeros.append(10)
numeros

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
numeros.extend(list(range(11,16)))
numeros

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

## Operações com sequências de listas

In [ ]:
[1,3] + [2,4]

[1, 3, 2, 4]

In [ ]:
[2,4] * 3

[2, 4, 2, 4, 2, 4]

In [ ]:
'Maíra ' + 'Santana'

'Maíra Santana'

# Matrizes

In [ ]:
# é uma lista de listas

m = [[1,2,3],[4,5,6],[7,8,9]]
m

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
# função para percorrer a matriz
def lerMatriz(matriz):
  linhas, colunas = (len(matriz), len(matriz[0]))
  print(linhas, colunas)
  for i in range(linhas):
    for j in range(colunas):
      print(matriz[i][j])

lerMatriz(m)

In [ ]:
numeros = list(range(1,11))
numeros

In [ ]:
soma = 0
for i in range(len(numeros)):
  soma = soma + numeros[i]
print(soma)

55


In [ ]:
teste_de_soma = sum(numeros)
print(teste_de_soma)

55


In [ ]:
import math
print(math.fsum(numeros))

55.0


## INICIALIZAÇÃO DE MATRIZES

In [ ]:
import numpy as np #biblioteca para manipulacao de dados
mA = np.zeros((3,5))
print(mA)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
mB = np.ones((3,5))
print(mB)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# matriz identidade
I = np.eye((5))
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# matriz diagonal
mC = np.diag([1,2,3,4])
print(mC)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
# abaixo ou acima da diagonal principal
mD = np.diag([1,1,1,1],-1)
print(mD)
print('\n')
mE = np.diag([1,1,1,1],+1)
print(mE)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [ ]:
# matriz aleatória
R = np.random.rand(3,5)
print(R)

[[0.61232957 0.26825777 0.2692352  0.59501939 0.58306728]
 [0.17417846 0.9250026  0.61385757 0.86359021 0.33658236]
 [0.18426045 0.81061495 0.59094403 0.54794378 0.99282255]]


In [ ]:
# matriz a partir de listas
L = [[1,2,3,4],[5,6,7,8]]
L = np.array(L) #converter a lista em um array
print(L)

[[1 2 3 4]
 [5 6 7 8]]


## ACESSAR ELEMENTOS DA MATRIZ

In [ ]:
L[1,3]

8

In [ ]:
# operador dois pontos
linha0 = L[[0],:]
print(linha0)
print(linha0.shape)

[[1 2 3 4]]
(1, 4)


In [ ]:
R[[0,2],:]

array([[0.61232957, 0.26825777, 0.2692352 , 0.59501939, 0.58306728],
       [0.18426045, 0.81061495, 0.59094403, 0.54794378, 0.99282255]])

In [ ]:
mD[0:3,:]

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

dá pra fazer a mesma coisa com as colunas

## Multiplicação de matrizes

In [ ]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1],[2],[3]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B

array([[1],
       [2],
       [3]])

In [ ]:
A @ B #multiplicacao

array([[14],
       [32],
       [50]])

In [ ]:
B @ B

ValueError: ignored

In [ ]:
# pode calcular a transposta
B.T @ B

array([[14]])

In [ ]:
print(B.T)

[[1 2 3]]
